FROM rabbitmq:3.8.16-management

RUN apt-get update && \
apt-get install -y curl unzip

RUN curl -L https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.8.9/rabbitmq_delayed_message_exchange-3.8.9-0199d11c.ez > rabbitmq_delayed_message_exchange.ez && \
mv rabbitmq_delayed_message_exchange.ez plugins/


RUN rabbitmq-plugins enable --offline rabbitmq_management  &&\
    rabbitmq-plugins enable --offline rabbitmq_shovel rabbitmq_shovel_management &&\
    rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange

# Management plugin ports
EXPOSE 15671 15672